env:
  browser: true
  es2021: true
  node: true

extends:
  - "eslint:recommended"
  - "prettier"

parserOptions:
  ecmaVersion: latest
  sourceType: "module"

rules:
  no-console: error
  camelcase: warn
  consistent-return: warn
  dot-notation: warn
  func-style: ["warn", "declaration"]
  prefer-const: warn
