name: Code quality

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: npm ci
      - name: Format files using prettier
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit possible changes
        with:
          commit_message: "Format files using prettier"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
