name: Publish extension in stores

on:
  release:
    types:
      - released

jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Download assets for release
        run: >
          gh release download ${{ github.ref }} --archive zip --dir assets --output source.zip
          gh release download ${{ github.ref }} --pattern "*firefox*" --dir assets
      - uses: browser-actions/release-firefox-addon@v0.1.3
        with:
          addon-id: "protoots"
          addon-path: "assets/protoots-firefox.zip"
          source-path: "assets/source.zip"
          approval-note: |
            The source code requires Node.js 18 or newer. To generate the source code, run:

            npm ci
            npm run package

            To check it's functionality, you can enable it on any Mastodon page, such as: https://mastodon.social/public
          license: OSL-3.0
          auth-api-issuer: ${{ secrets.FIREFOX_AUTH_API_ISSUER }}
          auth-api-secret: ${{ secrets.FIREFOX_AUTH_API_SECRET }}

  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Download assets for release
        run: gh release download ${{ github.ref }} --pattern "*chrome*" --dir assets
      - uses: browser-actions/release-chrome-extension@v0.1.2
        with:
          extension-id: "oocninmajklnpkmenhbfakbjcgahnidk"
          extension-path: "assets/protoots-chrome.zip"
          oauth-client-id: ${{ secrets.CHROME_OAUTH_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.CHROME_OAUTH_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.CHROME_OAUTH_REFRESH_TOKEN }}
